### ISSUE TITLE
Add the ability to change the 2FA mode

### ISSUE THREAD

**Issue by kymerea** [JJTech0130/pypush#24]
My apple account is connected with my home mac and some other macs (Beeper and other services), I do not have readily access to these mac's and as such using 2FA is a pain. There should in theory be a way to switch the 2FA mode to the phone number associated with the apple account. This is more of a 'nice to have' than actually being necessary, but would still be a good feature none the less.

**Comment by JJTech0130** [comment]
Unfortunately this is difficult to implement, because of the way we currently do authentication:

Modern Apple ID authentication uses an API called GSA (Grand Slam Authentication). However, in order to use this API you must generate some data using an algorithm called "Anisette". Similar to the "Absinthe" algorithm we emulate using Unicorn, it is highly obfuscated and would require another complex emulation system.

Our current solution side-steps this issue by using legacy APIs. They take advantage of the compatibility feature that allows you to append the 2FA code to the end of the password, but it means we get no choices about where to send the 2FA code.

If you can't access a trusted device, App Specific Passwords do work, so you could generate one of those.

In the future, we may end up needing to move to GSA if Apple removes or limits the old API, and I have already written some software to use it: https://github.com/JJTech0130/grandslam. For now, the old API is simpler and more reliable.

**Comment by kymerea** [comment]
Ah okay that makes sense. 
Hopefully we won't have to move over to Anisette as that would require a lot of effort.
Thanks though
